invoke_insn_hfence_gvma:
    .word 1656029299
    ret
invoke_insn_hfence_vvma:
    .word 582287475
    ret
invoke_insn_hlv_b:
    .word 1622491251
    ret
invoke_insn_hlv_bu:
    .word 1622491251
    ret
invoke_insn_hlv_h:
    .word 1689600115
    ret
invoke_insn_hlv_hu:
    .word 1689600115
    ret
invoke_insn_hlvx_hu:
    .word 1689600115
    ret
invoke_insn_hlv_w:
    .word 1756708979
    ret
invoke_insn_hlvx_wu:
    .word 1756708979
    ret
invoke_insn_hsv_b:
    .word 1644512627
    ret
invoke_insn_hsv_h:
    .word 1711621491
    ret
invoke_insn_hsv_w:
    .word 1778730355
    ret
invoke_insn_hlv_wu:
    .word 1756708979
    ret
invoke_insn_hlv_d:
    .word 1823817843
    ret
invoke_insn_hsv_d:
    .word 1845839219
    ret
